version: '3.8'

services:

  db:
    container_name: db
    image: postgres:13.7-alpine
    ports:
      - '5432:5432'
    volumes:
      - db-analog:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'analog'